### ISSUE TITLE
Packed Compressed Sparse Row (PCSR) 

### ISSUE THREAD

**Issue by marvin-hansen** [s1ck/graph#108]
Any aspirations to add PCSR, maybe as an option?

From the article: 
"...PCSR was orders of magnitude faster for inserts and updates than CSR
and adjacency list while maintaining similar graph traversal times." 

http://supertech.csail.mit.edu/papers/WheatmanXu18.pdf

IMHO, space (memory) is easier to solve than the long time it takes to generate a graph from a large dataset. 

Thoughts?

**Comment by marvin-hansen** [comment]
The python code from the publication:

https://github.com/wheatman/Packed-Compressed-Sparse-Row

**Comment by s1ck** [comment]
@marvin-hansen Thanks for the suggestion and sorry for the late reply (was busy with other things). I will have a look at the paper and get back to you.

**Comment by marvin-hansen** [comment]
I moved to PetGraph since its a rather mature graph lib for Rust.
