### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by makkus** [s1ck/graph#109]
Hi there, quick question: do you have any plans to release graph-mate as conda package on conda-forge? I know I could just `pip install` it in a conda environment, but for my use-case a native conda package would be a better fit.

If not, no worries, I might give it a go myself. Just never packaged a package with rust bindings.

**Comment by s1ck** [comment]
Hey! We haven't plan to do a dedicated conda release (yet). Feel free to try it out and report how it goes :)
