### ISSUE TITLE
Associated Edge Data

### ISSUE THREAD

**Issue by Kixiron** [s1ck/graph#4]
I'm looking at `graph` for backing a RVSDG implementation which is centered around edge "kinds" that hold various data, ex a value edge or a control flow edge. The ability to store data within edges and to query against it effectively (sometimes you just want to see state nodes from a given source to destination) is essential for that, so that'd be a really great addition.
This also requires the ability to have multiple (possibly identical) edges going between nodes and the multiplicity of the edges being retained, if that's a concern.
Thanks!

**Comment by s1ck** [comment]
@Kixiron feel free to reopen if you don't think that the current state of the crate is sufficient for your use case.
